name: Testing

on:
    push:
    workflow_dispatch:

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version:
                    - '7.4'
        steps:

            -   uses: actions/checkout@v1

            -   name: Configure DDEV
                run: ddev config --php-version ${{ matrix.php-version }}

            -   name: Start DDEV
                run: ddev start
